# Generated by Django 5.2.3 on 2025-06-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirr_data', '0002_salestransaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salestransaction',
            unique_together={('bill_no', 'date', 'item_name')},
        ),
    ]
